
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 45;
  public static final int STRING_LITERAL = 3;
  public static final int LBRACKET = 38;
  public static final int GREATER_OR_EQUAL = 54;
  public static final int NOT_EQUAL = 56;
  public static final int XOR = 51;
  public static final int INTEGER = 25;
  public static final int GREATER = 48;
  public static final int LPAREN = 34;
  public static final int ARRAY = 29;
  public static final int LESS = 47;
  public static final int MINUS = 43;
  public static final int FOR = 11;
  public static final int RPAREN = 35;
  public static final int REVERSE = 24;
  public static final int BOOLEAN_LITERAL = 6;
  public static final int NOT = 53;
  public static final int AND = 49;
  public static final int REAL_LITERAL = 5;
  public static final int SEMICOLON = 33;
  public static final int IS = 22;
  public static final int RANGE = 57;
  public static final int RECORD = 28;
  public static final int LESS_OR_EQUAL = 55;
  public static final int TYPE = 14;
  public static final int OR = 50;
  public static final int IN = 12;
  public static final int COMMA = 41;
  public static final int MULTIPLY = 44;
  public static final int PLUS = 42;
  public static final int LOOP = 20;
  public static final int ASSIGN = 32;
  public static final int IF = 8;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 27;
  public static final int RETURN = 15;
  public static final int EQUAL = 46;
  public static final int RBRACKET = 39;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int ROUTINE = 13;
  public static final int MOD = 52;
  public static final int REAL = 26;
  public static final int COLON = 31;
  public static final int LBRACE = 36;
  public static final int ELSE = 9;
  public static final int WHILE = 10;
  public static final int RBRACE = 37;
  public static final int THEN = 19;
  public static final int END = 18;
  public static final int STRING = 30;
  public static final int FALSE = 17;
  public static final int AS = 23;
  public static final int VAR = 7;
  public static final int PRINT = 21;
  public static final int INTEGER_LITERAL = 4;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "REAL_LITERAL",
  "BOOLEAN_LITERAL",
  "VAR",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "IN",
  "ROUTINE",
  "TYPE",
  "RETURN",
  "TRUE",
  "FALSE",
  "END",
  "THEN",
  "LOOP",
  "PRINT",
  "IS",
  "AS",
  "REVERSE",
  "INTEGER",
  "REAL",
  "BOOLEAN",
  "RECORD",
  "ARRAY",
  "STRING",
  "COLON",
  "ASSIGN",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "COMMA",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "EQUAL",
  "LESS",
  "GREATER",
  "AND",
  "OR",
  "XOR",
  "MOD",
  "NOT",
  "GREATER_OR_EQUAL",
  "LESS_OR_EQUAL",
  "NOT_EQUAL",
  "RANGE"
  };
}

