
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int STRING_LITERAL = 50;
  public static final int LBRACKET = 9;
  public static final int XOR = 44;
  public static final int NOT_EQUAL = 13;
  public static final int INTEGER = 40;
  public static final int LPAREN = 7;
  public static final int GREATER = 16;
  public static final int ARRAY = 47;
  public static final int LESS = 14;
  public static final int FOR = 31;
  public static final int MINUS = 3;
  public static final int REVERSE = 32;
  public static final int RPAREN = 8;
  public static final int REAL_LITERAL = 52;
  public static final int NOT = 43;
  public static final int AND = 41;
  public static final int SEMICOLON = 19;
  public static final int IS = 25;
  public static final int RANGE = 22;
  public static final int RECORD = 38;
  public static final int TYPE = 37;
  public static final int IN = 48;
  public static final int OR = 42;
  public static final int COMMA = 20;
  public static final int LESS_EQUAL = 15;
  public static final int LOOP = 33;
  public static final int PLUS = 2;
  public static final int ASSIGN = 11;
  public static final int IF = 27;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 12;
  public static final int TRUE = 45;
  public static final int GREATER_EQUAL = 17;
  public static final int error = 1;
  public static final int ROUTINE = 24;
  public static final int MODULO = 6;
  public static final int TIMES = 4;
  public static final int COLON = 18;
  public static final int ELSE = 29;
  public static final int READ = 35;
  public static final int WHILE = 30;
  public static final int THEN = 28;
  public static final int END = 26;
  public static final int STRING = 39;
  public static final int FALSE = 46;
  public static final int VAR = 23;
  public static final int PRINT = 34;
  public static final int INTEGER_LITERAL = 51;
  public static final int IDENTIFIER = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULO",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "ASSIGN",
  "EQUAL",
  "NOT_EQUAL",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "RANGE",
  "VAR",
  "ROUTINE",
  "IS",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "REVERSE",
  "LOOP",
  "PRINT",
  "READ",
  "RETURN",
  "TYPE",
  "RECORD",
  "STRING",
  "INTEGER",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "TRUE",
  "FALSE",
  "ARRAY",
  "IN",
  "IDENTIFIER",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "REAL_LITERAL"
  };
}

