
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
package parser;

public class sym {
  /* terminals */
  public static final int SEMICOLON = 17;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 22;
  public static final int REAL_LITERAL = 21;
  public static final int IDENTIFIER = 19;
  public static final int TRUE = 7;
  public static final int COLON = 18;
  public static final int LPAREN = 15;
  public static final int SUB = 10;
  public static final int BOOLEAN = 6;
  public static final int EOF = 0;
  public static final int DIV = 12;
  public static final int ADD = 9;
  public static final int FALSE = 8;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int ASSIGN = 13;
  public static final int EQ = 14;
  public static final int INTEGER_LITERAL = 20;
  public static final int INTEGER = 4;
  public static final int REAL = 5;
  public static final int MUL = 11;
  public static final int VAR = 3;
  public static final int MOD = 23;
  public static final int COMMA = 24;
  public static final int LT = 25;
  public static final int GT = 26;
  public static final int LEQ = 27;
  public static final int GEQ = 28;
  public static final int IF = 29;
  public static final int FOR = 30;
  public static final int ELSE = 31;
  public static final int WHILE = 32;
  public static final int RETURN = 33;
  public static final int ROUTINE = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "VAR",
  "INTEGER",
  "REAL",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "ASSIGN",
  "EQ",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COLON",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "REAL_LITERAL",
  "BOOLEAN_LITERAL",
  "MOD",
  "COMMA",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "IF",
  "FOR",
  "ELSE",
  "WHILE",
  "RETURN",
  "ROUTINE"
  };
}
